apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-blue
  namespace: demo
spec:
  maxReplicas: 7
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web-blue
  targetCPUUtilizationPercentage: 60